### ISSUE TITLE
Cannot convert value of type 'SkyFloatingLabelTextField' to expected argument type 'String'

### ISSUE THREAD

**Issue by ChristianEmilBach** [intonarumori/FloatingLabelTextField#2]
Hi. I wanted to make my login function using the cool designs from SkyFloatingTextFieldLabel as the textfield, but when I reached the point where I was gonna implement the actual login function itself, it got this error.. My code is currently placed inside the viewdidload because it can't fint the SkyFloatingTextFieldLabel that I named CUEmailTextfield outside of it. any help would be massively appreciated!!!
<img width="1501" alt="skaermbillede 2018-12-04 kl 20 15 01" src="https://user-images.githubusercontent.com/44226324/49467096-ec6ca900-f801-11e8-957d-e86573618d28.png">

**Comment by intonarumori** [comment]
Closing for now, this is related to `SkyFloatingLabelTextField`.
